//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COACHME.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_COMMENT
    {
        public int AUTO_ID { get; set; }
        public Nullable<int> USER_ROLE_ID { get; set; }
        public Nullable<int> COURSE_ID { get; set; }
        public string COMMENT { get; set; }
        public string COMMENT_BY { get; set; }
        public Nullable<System.DateTime> COMMENT_DATE { get; set; }
    
        public virtual COURSES COURSES { get; set; }
        public virtual MEMBER_ROLE MEMBER_ROLE { get; set; }
    }
}
