//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COACHME.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGON_ACTIVITY
    {
        public int AUTO_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string ACTION { get; set; }
        public string FULLNAME { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
