//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COACHME.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESET_PASSWORD
    {
        public int AUTO_ID { get; set; }
        public string USER_NAME { get; set; }
        public string TOKEN_HASH { get; set; }
        public Nullable<System.DateTime> TOKEN_EXPIRATION { get; set; }
        public Nullable<bool> TOKEN_USED { get; set; }
    }
}
