//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COACHME.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURVEYS
    {
        public int AUTO_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string RESPONSE_TYPE { get; set; }
        public Nullable<int> RESPONSE_COUNT { get; set; }
        public string RESPONSE_BY { get; set; }
        public Nullable<System.DateTime> RESPONSE_DATE { get; set; }
    }
}
